### PR TITLE
Greatly reduce the number of API calls

### PR DESCRIPTION
**Pull request by Janzert**
Combine all directly know steam ids into the minimum number of api
calls. Also query vanity urls only one time.

### CODE REVIEW

**Comment by ncla** [comment]
This looks so much better. A final thing to improve would be ditching vanity URL conversion completely since the page provides profile number in the source code anyway.

**Comment by Janzert** [comment]
ncla, your image shows an example of the case when where the checkbox is really a checkbox (i.e. class="friendCheckbox2") and the code already does pull that id out directly. The case when vanity urls are resolved is when the checkbox is really just an image (i.e. class="friendCheckbox"). In that case so far as I see if there is a vanity url there isn't anything else with the id already in the page.

**Comment by nicememe** [comment]
Thanks :D

**Comment by nicememe** [comment]
APIs not being executed. Not good with Git, accidentally merged. Will fix then merge again '_'

**Comment by ncla** [comment]
Ah, I didn't know that about players that are your friends with, I assumed they would have the same HTML structure as non-friends. Thanks for explaining.

**Pull request merged**
